services:
  nats:
    image: nats:latest
    container_name: chatroom-nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_CLUSTER_ADVERTISE=localhost
      - NATS_SERVER_NAME=nats-main
    command: ["-js"]